### ISSUE TITLE
Confirm dialog popup after executing command.

### ISSUE THREAD

**Issue by Mqxx** [ionutvmi/vscode-commands-executor#1]
Hey I'm using this extension right now and it works perfectly! Exactly what I was looking for. I only have one problem now. My startup command looks like this:

```json
"vscode-commands-executor.startupRules": [
    {
        "commands": [
            {
                "id": "workbench.action.clearRecentFiles",
            }
        ],
        "message": "Cleared recent files History.",
        "conditions": ["always"]
    }
]
```

Now I have the problem that when I run the whole thing I get a popup window where I have to confirm the whole thing. Can I confirm this automatically?

**Comment by mihai-vlc** [comment]
From what I can see the `clearRecentFiles` doesn't have a way of skipping the confirmation dialog.

https://github.com/microsoft/vscode/blob/83fc3ad9bd553869e8fea3d370d1d2bd438f9e54/src/vs/workbench/browser/parts/editor/editorActions.ts#L1574

**Comment by Mqxx** [comment]
Okay. Thanks for the reply and research.
